title: Pranay Ellendra
logo: /assets/pranay.jpg
description: Full Stack Developer
Contact Information:
Contact_E-mail: ellendrapranay@gmail.com
Linkedin: fbjbdj
Mobile_Number: 513-290-6100
Resume: /assets/Pranay_Ellendra.docx
theme: jekyll-theme-minimal
